// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiejtairiylxpxwkghsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZWp0YWlyaXlseHB4d2tnaHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMzc4OTMsImV4cCI6MjA5MDYxMzg5M30.qEwgN9YXVSHs-jzu9nr1V1iM36neRr-cpmVuPdMpO-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});